<a href="https://colab.research.google.com/github/aravindrepository/PYTHON_learning/blob/main/Mathematics_for_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


declraing scalars and vectors

In [3]:
#scalar
s=5
s

5

In [4]:
#vector
v=np.array([12,3,5])
v

array([12,  3,  5])

In [5]:
#matrix
m=np.array([[1,2,3],[4,5,6]])
m


array([[1, 2, 3],
       [4, 5, 6]])

shape returns shape of the data

In [7]:
m.shape
#reshape
v.reshape(3,1)


array([[12],
       [ 3],
       [ 5]])

TEnSors


In [13]:
m1=np.array([[1,2,3],[5,6,7]])
m1
m2=np.array([[9,8,7],[7,6,5]])
m2
ten=np.array([m1,m2])
ten
ten.shape

(2, 2, 3)

In [14]:
m1 + m2

array([[10, 10, 10],
       [12, 12, 12]])

In [15]:
m1 - m2

array([[-8, -6, -4],
       [-2,  0,  2]])

In [16]:
m1 * m2

array([[ 9, 16, 21],
       [35, 36, 35]])

Transpose

In [20]:
m2

array([[9, 8, 7],
       [7, 6, 5]])

DOT PRODUCT

In [23]:
n1=np.array([1,2,3])
n2=np.array([4,5,6])
np.dot(n1,n2)

32