<a href="https://colab.research.google.com/github/aravindrepository/PYTHON_learning/blob/main/numPY_Pandas_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=[1,2,3]
np.array(a)
# or a=np.array([1,2,3])

array([1, 2, 3])

In [4]:
a2=np.array([[1,2,3],[4,5,6],[9,8,10]])
a2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 9,  8, 10]])

In [11]:
np.mean(a)
np.median(a)
np.mean(a2)
np.median(a2)


5.0

In [14]:
np.mean(a2,axis=1)
#means of all rows
# axis=1 means rows

array([2., 5., 9.])

In [15]:
np.mean(a2,axis=0)
#means of all columns axis=0 meanscolumns

array([4.66666667, 5.        , 6.33333333])

In [19]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [20]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [21]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [25]:
np.linspace(1,2,11)
#creates data from start 1 to end 2 with give n no of steps

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ])

In [26]:
np.eye(5)
#creates identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
np.random.randint(4,10,10)
#gens random numbers within start and stop '2'/step gives n no of numbers

array([9, 4, 6, 6, 7, 8, 4, 5, 7, 8])