<a href="https://colab.research.google.com/github/aravindrepository/PYTHON_learning/blob/main/numPY_Pandas_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import pandas as pd

In [ ]:
a=[1,2,3]
np.array(a)
# or a=np.array([1,2,3])

array([1, 2, 3])

In [ ]:
a2=np.array([[1,2,3],[4,5,6],[9,8,10]])
a2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 9,  8, 10]])

In [12]:
np.mean(a)
np.median(a)
np.mean(a2)
np.median(a2)


NameError: name 'a' is not defined

In [ ]:
np.mean(a2,axis=1)
#means of all rows
# axis=1 means rows

array([2., 5., 9.])

In [ ]:
np.mean(a2,axis=0)
#means of all columns axis=0 meanscolumns

array([4.66666667, 5.        , 6.33333333])

In [ ]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.linspace(1,2,11)
#creates data from start 1 to end 2 with give n no of steps

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ])

In [ ]:
np.eye(5)
#creates identity matrix

dtype('float64')

In [ ]:
np.random.randint(4,10,10)
#gens random numbers within start and stop '2'/step gives n no of numbers

array([9, 4, 6, 6, 7, 8, 4, 5, 7, 8])

pandas


In [ ]:
import pandas as pd
p=['a','b','c']
pd.Series(p)

0    a
1    b
2    c
dtype: object

In [ ]:
work_experience_years = pd.Series([5,8,3,10])
work_experience_years.name = "Work Experience (Yrs.)"
work_experience_years.name

'Work Experience (Yrs.)'

In [2]:
workers_age={
    'Amy White': 50,
    'Jack Stewart': 53,
    'Richard Lauderdale': 35,
    'Sara Jhonson': 43
}

In [7]:
workers_age=pd.Series(workers_age)
workers_age

Amy White             50
Jack Stewart          53
Richard Lauderdale    35
Sara Jhonson          43
dtype: int64

In [8]:
workers_age.index

Index(['Amy White', 'Jack Stewart', 'Richard Lauderdale', 'Sara Jhonson'], dtype='object')

In [9]:
workers_age.min()

35

In [10]:
workers_age.max()

53

In [11]:
workers_age.median()

46.5

In [13]:
workers_age.idxmax()

'Jack Stewart'

In [14]:


employees_work_exp = pd.Series({
'Amy White'   : 3,
'Jack Stewart'   : 5,
'Richard Lauderdale'  : 4.5,
'Sara Johnson'  : 22,
'Patrick Adams' : 28,
'Jessica Baker'  : 14,
'Peter Hunt'   : 4,
'Daniel Lloyd'  : 6,
'John Owen'   : 1.5,
'Jennifer Phillips'  : 10,
'Courtney Rogers'   : 4.5,
'Anne Robinson'  : 2,
})
employees_work_exp.head()

Amy White              3.0
Jack Stewart           5.0
Richard Lauderdale     4.5
Sara Johnson          22.0
Patrick Adams         28.0
dtype: float64

In [15]:
employees_work_exp.tail()

Daniel Lloyd          6.0
John Owen             1.5
Jennifer Phillips    10.0
Courtney Rogers       4.5
Anne Robinson         2.0
dtype: float64